EnglishWordsLearning.Web/Controllers/FlashCardsController.cs
using EnglishWordsLearning.Application.Common;
using Microsoft.AspNetCore.Mvc;


namespace EnglishWordsLearning.Web.Controllers;

public class FlashCardsController : Controller
{
    public async Task<IActionResult> Index(string level = "AllLevels")
    {
        var words = await LoadWordsHelper.LoadCsvWordsAsync(level);
        
        var randomWord = LoadWordsHelper.GetRandomWord(words);
        
        ViewBag.DisplayedLevel = LoadWordsHelper.Levels[level];
        ViewBag.SelectedLevel = level;
        
        return View(randomWord);
    }
}

EnglishWordsLearning.Web/Controllers/HistoryLogsController.cs
using EnglishWordsLearning.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace EnglishWordsLearning.Web.Controllers;

public class HistoryLogsController : Controller
{
    private readonly IHistoryLogsService _historyLogsService;

    public HistoryLogsController(IHistoryLogsService historyLogsService)
    {
        _historyLogsService = historyLogsService;
    }

    public IActionResult HistoryLogsOfTests()
    {
        var historyLogs = _historyLogsService.GetHistoryLogs();

        return View(historyLogs);
    }
}

EnglishWordsLearning.Web/Controllers/TestController.cs
using EnglishWordsLearning.Application.Common;
using EnglishWordsLearning.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using EnglishWordsLearning.Core.Models;

namespace EnglishWordsLearning.Web.Controllers;

public class TestController : Controller
{
    private readonly IHistoryLogsService _historyLogsService;
    private readonly IMyMemoryService _myMemoryService;

    public TestController(IHistoryLogsService historyLogsService, IMyMemoryService myMemoryService)
    {
        _historyLogsService = historyLogsService;
        _myMemoryService = myMemoryService;
    }

    public async Task<IActionResult> CheckTranslation(string userLanguage = "Spanish", string level = "AllLevels")
    {
        if (!LoadWordsHelper.Levels.ContainsKey(level))
        {
            return BadRequest("Invalid level");
        }

        ViewBag.LanguageDictionary = LanguageDictionary.GetLanguageDictionary();
        ViewBag.UserLanguage = userLanguage;
        ViewBag.DisplayedLevel = LoadWordsHelper.Levels[level];
        ViewBag.SelectedLevel = level;

        var randomWord = await GetRandomTranslatedWord(LanguageDictionary.GetLanguage(userLanguage), level);

        return View(randomWord);
    }

    [HttpPost]
    public async Task<IActionResult> CheckTranslation(string englishWord, string userTranslation, string level, string userLanguage)
    {
        if (!LoadWordsHelper.Levels.ContainsKey(level))
        {
            return BadRequest("Invalid level");
        }

        ViewBag.LanguageDictionary = LanguageDictionary.GetLanguageDictionary();
        var words = await LoadWordsHelper.LoadCsvWordsAsync(level);
        var word = words.FirstOrDefault(w => w.English == englishWord);

        int correctAnswers = HttpContext.Session.GetInt32("correctAnswers") ?? 0;
        int totalQuestions = HttpContext.Session.GetInt32("totalQuestions") ?? 0;

        if (word != null)
        {
            totalQuestions++;
            if (word.English.Equals(userTranslation.Trim(), StringComparison.OrdinalIgnoreCase))
            {
                correctAnswers++;
                ViewBag.Result = "Correct!";
            }
            else
            {
                ViewBag.Result = $"Incorrect. The correct translation is: {word.English}";
            }
        }

        // Save correct answers and total questions back to session
        HttpContext.Session.SetString("level", LoadWordsHelper.Levels[level]);
        HttpContext.Session.SetString("userLanguage", userLanguage);
        HttpContext.Session.SetInt32("correctAnswers", correctAnswers);
        HttpContext.Session.SetInt32("totalQuestions", totalQuestions);

        // Pass the result and count to the view
        ViewBag.DisplayedLevel = LoadWordsHelper.Levels[level];
        ViewBag.SelectedLevel = level;
        ViewBag.UserLanguage = userLanguage;
        ViewBag.CorrectAnswers = correctAnswers;
        ViewBag.TotalQuestions = totalQuestions;

        var randomWord = await GetRandomTranslatedWord(LanguageDictionary.GetLanguage(userLanguage), level);

        return View(randomWord);
    }

    public IActionResult FinishTranslation()
    {
        if (User.Identity != null && User.Identity.IsAuthenticated)
        {
            int totalQuestions = HttpContext.Session.GetInt32("totalQuestions") ?? 0;
            int correctAnswers = HttpContext.Session.GetInt32("correctAnswers") ?? 0;
            double resultInPercentage = totalQuestions > 0 ? (double)correctAnswers / totalQuestions * 100 : 0.0;
            string level = HttpContext.Session.GetString("level") ?? "AllLevels";
            string username = ViewBag.Username;

            _historyLogsService.HistoryLogsOfTestsAdd(totalQuestions, correctAnswers, resultInPercentage, username, level);
        }
        
        HttpContext.Session.Remove("level");
        HttpContext.Session.Remove("userLanguage");
        HttpContext.Session.Remove("correctAnswers");
        HttpContext.Session.Remove("totalQuestions");

        return RedirectToAction("CheckTranslation");
    }

    private async Task<Word> GetRandomTranslatedWord(string userLanguage, string level)
    {
        var words = await LoadWordsHelper.LoadCsvWordsAsync(level);
        var randomWord = LoadWordsHelper.GetRandomWord(words);
        var translation = await _myMemoryService.TranslateAsync(userLanguage, randomWord.English);
        randomWord.Translation = translation;
        return randomWord;
    }
}

EnglishWordsLearning.Web/Controllers/WordsController.cs
using EnglishWordsLearning.Application.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace EnglishWordsLearning.Web.Controllers;

[Authorize]
public class WordsController : Controller
{
    public async Task<IActionResult> Index(string? searchTerm = null, string level = "AllLevels")
    {
        var words = await LoadWordsHelper.LoadCsvWordsAsync();
            
        words = words.Where(w => w.Level == level || level == "AllLevels" && w.English == searchTerm || searchTerm == null).ToList();
            
        return View(words);
    }

        
        
    /*
    public IActionResult AddWord()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddWord(Word wordViewModel)
    {
        if (ModelState.IsValid)
        {
            wordViewModel.Id = Guid.NewGuid();
            var words = await LoadWordsHelper.LoadJsonWordsAsync();
            words.Add(wordViewModel);

            // Save updated words back to the file
            var json = JsonConvert.SerializeObject(words, Formatting.Indented);
            await System.IO.File.WriteAllTextAsync(LoadWordsHelper.JsonWordsFilePath, json);

            return RedirectToAction("Index");
        }

        return View(wordViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> RemoveWord(Guid id)
    {
        var words = await LoadWordsHelper.LoadJsonWordsAsync();
        var wordToRemove = words.FirstOrDefault(w => w.Id == id);
        if (wordToRemove != null)
        {
            words.Remove(wordToRemove);

            // Save updated words back to the file
            var json = JsonConvert.SerializeObject(words, Formatting.Indented);
            await System.IO.File.WriteAllTextAsync(LoadWordsHelper.JsonWordsFilePath, json);

            return RedirectToAction("Index");
        }

        return NotFound();
    }

    */
}

EnglishWordsLearning.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EnglishWordsLearning</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EnglishWordsLearning.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EnglishWordsLearning</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Words" asp-action="Index">Words</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FlashCards" asp-action="Index">FlashCards</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="CheckTranslation">Check Translation</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Profile
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                @if (User.Identity is { IsAuthenticated: true })
                                {
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-username="@ViewBag.Username">Profile</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="SignOut">Sign Out</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="HistoryLogs" asp-action="HistoryLogsOfTests">History</a></li>
                                }
                                @if (User.Identity is { IsAuthenticated: false })
                                {
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="SignIn">Sign In</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="SignUp">Sign Up</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="HistoryLogs" asp-action="HistoryLogsOfTests">History</a></li>
                                }
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="padding-bottom: 60px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            <a href="https://github.com/sentemon/EnglishWordsLearning/" target="_blank" class="github-icon">
                <svg viewBox="0 0 496 512" height="3em" width="3em" class="github-svg">
                    <path
                        d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"
                    ></path>
                </svg>
            </a>
            &copy; @DateTime.Now.Year - EnglishWordsLearning
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>